version: "2.1"

services:
    php:
#        restart: always
        build:
            context: ./services/php
            dockerfile: Dockerfile
        image:          "${PREFIX_IMAGE}_php"
        container_name: "${PREFIX_CONTAINER}_php"
        hostname:       "${PREFIX_CONTAINER}_php"
        expose:
            - "${XDEBUG_PORT:-9000}"
        ports:
            - "${HOST_PORT_APP:-8080}:80"
        environment:
            - HOST_PORT_APP=${HOST_PORT_APP:-8080}
        env_file:
            - .env
            - envs/common.env
        volumes:
            - ./services/php/app:/app
            - ./services/php/ini/zz_xdebug.ini:${DIR_PHP}/conf.d/zz_xdebug.ini
            - ${HOST_DIR_ARC}:${DIR_ARC}
            - ${HOST_DIR_SRC}:${DIR_SRC}
            - ${HOST_DIR_WEB_ROOT}:${DIR_WEB_ROOT}
        working_dir: "${DIR_SRC}"
        entrypoint: ["/app/bin/entrypoint.sh"]
