version: "2.1"

services:
    php:
#        restart: always
        build:
            context: ./services/php
            dockerfile: Dockerfile
        image:          "${PREFIX_IMAGE}_php"
        container_name: "${PREFIX_CONTAINER}_php"
        hostname:       "${PREFIX_CONTAINER}_php"
        expose:
            - "${XDEBUG_PORT:-9000}"
        ports:
            - "${APP_PORT_HOST:-8080}:80"
        environment:
            - APP_PORT_HOST=${APP_PORT_HOST:-8080}
        env_file:
            - .env
            - envs/common.env
        volumes:
            - ./services/php/app:/app
            - ./services/php/ini/zz_xdebug.ini:${DIR_PHP}/conf.d/zz_xdebug.ini
            - ${DIR_ARC_HOST}:${DIR_ARC}
            - ${DIR_SRC_HOST}:${DIR_SRC}
            - ${DIR_DATA_HOST}/html:${DIR_WWW_ROOT}
        working_dir: "${DIR_SRC}"
        entrypoint: ["/app/bin/entrypoint.sh"]
